### ISSUE TITLE
hra nejde zapnout

### ISSUE THREAD

**Issue by GamakCZ** [kvetinac97/Sudoku#1]
nejde vytvořit novou hru

**Comment by kvetinac97** [comment]
jj, není to ještě hotové 👍 ale díky že to kontroluješ, budu mít nějakou odezvu

**Comment by kvetinac97** [comment]
Hotovo! Můžeš testovat 😄

**Comment by GamakCZ** [comment]
a jak? 🤔 

![image](https://user-images.githubusercontent.com/17053298/54317392-4b9d3f00-45e3-11e9-9c3b-f796fec2af9c.png)
